# Generated by Django 4.2.3 on 2023-08-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=60, unique=True)),
                ('registration_date', models.DateField()),
                ('last_login', models.DateField()),
                ('phone_number', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'clients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('country_phone_code', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'countries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
            ],
            options={
                'db_table': 'currencies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Exchanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
            ],
            options={
                'db_table': 'exchanges',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='')),
                ('photo_date', models.DateField()),
                ('photo_comment', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'photos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('open', models.PositiveIntegerField()),
                ('low', models.PositiveIntegerField()),
                ('high', models.PositiveIntegerField()),
                ('close', models.PositiveIntegerField()),
                ('volume', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'prices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('symbol', models.CharField(max_length=225)),
            ],
            options={
                'db_table': 'stocks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('trade_date', models.DateField()),
                ('position', models.CharField(blank=True, choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=45, null=True)),
                ('outcome', models.CharField(blank=True, choices=[('success', 'Success'), ('failed', 'Failed'), ('neutral', 'Neutral')], max_length=45, null=True)),
                ('trade_type', models.CharField(blank=True, choices=[('normal', 'Normal'), ('options', 'Options'), ('futures', 'Futures')], max_length=45, null=True)),
                ('expiry', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trades',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
        migrations.DeleteModel(
            name='Exchange',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
