# Generated by Django 4.2.3 on 2023-07-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortApp', '0002_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/')),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('trade_date', models.DateField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=45, null=True)),
                ('outcome', models.CharField(blank=True, max_length=45, null=True)),
                ('trade_type', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'photos',
                'managed': False,
            },
        ),
    ]
