# Generated by Django 4.2.3 on 2023-09-05 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PortApp', '0003_n'),
    ]

    operations = [
        migrations.DeleteModel(
            name='N',
        ),
    ]
